apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: zabbix-agent
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: zabbix-agent
  template:
    metadata:
      labels:
        app: zabbix-agent
    spec:
      hostNetwork: true
      hostPID: true
      containers:
      - name: zabbix-agent
        image: zabbix/zabbix-agent2:alpine-7.0-latest
        ports:
        - containerPort: 10050
          name: zabbix-agent
        env:
        - name: ZBX_SERVER_HOST
          value: zabbix-server.monitoring.svc.cluster.local
        - name: ZBX_HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: ZBX_PASSIVE_ALLOW
          value: "true"
        - name: ZBX_ACTIVE_ALLOW
          value: "true"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        securityContext:
          privileged: true
